### ISSUE TITLE
Single artifact

### ISSUE THREAD

**Issue by mishako** [rometools/rome2#4]
**Pros**
- Easier to use
- Easier to develop

**Cons**
- Users who care about disk space can pick only the parts they need

Currently the size of `rome.jar` is ~250K (includes `rome-utils`). The size of `rome-modules.jar` is ~520K (includes `rome` and `rome-utils`).

**Comment by imk** [comment]
The file size (250k or 500k) shouldn't be a major issue, so there's nothing wrong with a single jar.

I prefer multiple modules because it's easier to enforce separation of concerns in different modules (like API, Repository etc.) but you can enforce your architecture rules on others ways too.

Easier to use: Most people are using some sort of dependency management tools, so transitive dependencies are managed by a tool and not by hand.

So both ways are valid, when we want to enforce some rules for the structure of the software, multiple modules could be helpful. If requests or helpful, we also could build a single jar from multiple modules.

For development, it may be harder to find the right module where to implement a specific feature or where to fix a bug. But maybe it's also easier to understand a small module focused on a single concern.

**Pros**

* small modules are easier to understand
* easier to enforce structure rules

**Cons**

* Module structure ist harder to understand
* more config boilerplate

**Comment by mishako** [comment]
@imk I think these are two different decisions:
1. How we package the library for the users
2. How we organize our code

The first one is what I mean when I say "single artifact". The "easier to use" is about the user not being forced to decide which artifacts to depend on. I hate when it's not obvious which one of [20+ jackson artifacts](http://search.maven.org/#search%7Cga%7C1%7Ccom.fasterxml.jackson) I need when I want to parse a simple json. Of course jackson is a very advanced library with many use cases, so they have to split it into many artifacts. I don't think we have to.

The second one is what I think you're talking about. And I think it's too early to decide. We can always do it later during development, when we see that the codebase has become to big for a single module. At that stage we probably have a very good structure in form of java packages, which is then easily convertible into a multi-module project.

**Comment by imk** [comment]
Oh, ok, I see the difference now. I had really just been thinking about an 1:1 relation between *code organization module* and jars.

**Comment by mishako** [comment]
Okay, this doesn't seem to be controversial, so I'm closing the ticket. We will start with a single artifact and see where it takes us.
